//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_DrivingLic
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string Class { get; set; }
        public string No { get; set; }
        public System.DateTime Exprires { get; set; }
    }
}
