//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Function
    {
        public int Id { get; set; }
        public int IdParent { get; set; }
        public string DisplayName { get; set; }
        public string ControlName { get; set; }
        public Nullable<int> Prioritize { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Images { get; set; }
    }
}
