//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Sign
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string ImgName { get; set; }
        public byte ImgType { get; set; }
        public Nullable<int> WidImg { get; set; }
        public Nullable<int> HgtImg { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public string FontName { get; set; }
        public Nullable<double> FontSize { get; set; }
        public string FontType { get; set; }
        public string FontColor { get; set; }
    }
}
