//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_User
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public string SecondaryPassword { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string IdDepartment { get; set; }
        public string DisplayNameVN { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CitizenID { get; set; }
        public string Nationality { get; set; }
        public string JobCode { get; set; }
        public string PCName { get; set; }
        public string IPAddress { get; set; }
        public string Addr { get; set; }
        public string PhoneNum1 { get; set; }
        public string PhoneNum2 { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Sex { get; set; }
    }
}
