//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Watermark
    {
        public int ID { get; set; }
        public string DisplayName { get; set; }
        public string Describe { get; set; }
        public string PicImage { get; set; }
        public Nullable<int> Rotation { get; set; }
        public Nullable<int> Scale { get; set; }
        public Nullable<int> Opacity { get; set; }
        public Nullable<int> VertDistance { get; set; }
        public Nullable<int> HoriDistance { get; set; }
    }
}
