//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt207_Security_BAK
    {
        public int Id { get; set; }
        public string IdKnowledgeBase { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public string IdUser { get; set; }
        public Nullable<bool> ReadInfo { get; set; }
        public Nullable<bool> UpdateInfo { get; set; }
        public Nullable<bool> DeleteInfo { get; set; }
        public Nullable<bool> SearchInfo { get; set; }
        public Nullable<bool> ReadFile { get; set; }
        public Nullable<bool> SaveFile { get; set; }
    }
}
