//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt202_Base
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> TypeOf { get; set; }
        public string Keyword { get; set; }
        public string RequestUsr { get; set; }
        public int IdFile { get; set; }
        public System.DateTime UploadTime { get; set; }
        public string UsrUpload { get; set; }
    }
}
