//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt201_ReqUpdateDocs
    {
        public int Id { get; set; }
        public string TypeChange { get; set; }
        public string Category { get; set; }
        public string Content { get; set; }
        public string DocCode { get; set; }
        public string Descript { get; set; }
        public int DeadLine { get; set; }
    }
}
