//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt206_Documents
    {
        public int Id { get; set; }
        public string IdDept { get; set; }
        public int IdCategory { get; set; }
        public Nullable<int> IdUseFor { get; set; }
        public string DocumentCode { get; set; }
        public string DisplayNameVN { get; set; }
        public string DisplayNameZH { get; set; }
        public string DisplayNameEN { get; set; }
        public Nullable<bool> HasCopyright { get; set; }
        public string VersionNo { get; set; }
        public int IdAttachment { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> RemoveAt { get; set; }
        public string RemoveBy { get; set; }
    }
}
