//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt207_HistoryGetFile
    {
        public int Id { get; set; }
        public System.DateTime TimeGet { get; set; }
        public string TypeGet { get; set; }
        public string IdKnowledgeBase { get; set; }
        public string KnowledgeAttachmentName { get; set; }
        public string IdUser { get; set; }
    }
}
