//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt201_UpdateUsrReq
    {
        public int Id { get; set; }
        public string IdDept { get; set; }
        public string IdUsr { get; set; }
        public string TypeChange { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Describe { get; set; }
    }
}
