//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt204_InternalDocMgmt
    {
        public int Id { get; set; }
        public string IdDept { get; set; }
        public int IdDocCatorary { get; set; }
        public int IdFuncCatorary { get; set; }
        public string DocLevel { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameVN { get; set; }
        public string DocVersion { get; set; }
        public System.DateTime DeployDate { get; set; }
        public int PeriodNotify { get; set; }
        public Nullable<int> PauseNotify { get; set; }
        public string IdFounder { get; set; }
        public string IdUsrUpload { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int IdAtt { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> DelTime { get; set; }
        public string IdUsrDel { get; set; }
        public string MainCatorary { get; set; }
        public string SubDept { get; set; }
    }
}
