//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt207_DocProcessing
    {
        public int Id { get; set; }
        public string IdKnowledgeBase { get; set; }
        public int IdProgress { get; set; }
        public bool IsComplete { get; set; }
        public bool IsSuccess { get; set; }
        public string Descriptions { get; set; }
        public string IdUserProcess { get; set; }
        public string Change { get; set; }
    }
}
