//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt201_Base
    {
        public int Id { get; set; }
        public int IdParent { get; set; }
        public int IdGroup { get; set; }
        public string DocCode { get; set; }
        public string DisplayName { get; set; }
    }
}
