//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt205_Base
    {
        public int Id { get; set; }
        public int IdParent { get; set; }
        public string IdDept { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameVN { get; set; }
        public string DisplayNameEN { get; set; }
        public string DocType { get; set; }
        public bool Confidential { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> NotifyCycle { get; set; }
        public Nullable<int> PreAlertMonths { get; set; }
        public bool IsFinalNode { get; set; }
        public Nullable<System.DateTime> RemoveAt { get; set; }
        public string RemoveBy { get; set; }
    }
}
