//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt205_Form
    {
        public int Id { get; set; }
        public int BaseId { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string CreateBy { get; set; }
        public string Note { get; set; }
    }
}
