//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt201_ProgInfo
    {
        public int Id { get; set; }
        public int IdForm { get; set; }
        public string IdUsr { get; set; }
        public string Desc { get; set; }
        public System.DateTime RespTime { get; set; }
        public Nullable<System.DateTime> SendNoteTime { get; set; }
    }
}
