//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt201_UpdateUsrReq_Detail
    {
        public int Id { get; set; }
        public int IdUpdateReq { get; set; }
        public int IdReq { get; set; }
        public System.DateTime DeadLine { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string UsrComplete { get; set; }
        public Nullable<System.DateTime> TimeSendNote { get; set; }
        public string UsrConfirm { get; set; }
    }
}
