//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt207_NotifyEditDoc
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeNotify { get; set; }
        public int IdDocProcess { get; set; }
        public string IdUserNotify { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> TimeNotifyNotes { get; set; }
    }
}
