//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt306_Base
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string UploadUsr { get; set; }
        public System.DateTime UploadDate { get; set; }
        public bool IsProcess { get; set; }
        public bool IsCancel { get; set; }
        public string NextStepProg { get; set; }
        public string Desc { get; set; }
        public int IdType { get; set; }
        public bool Confidential { get; set; }
    }
}
