//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt302_Base
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public string Supervisor { get; set; }
        public string School { get; set; }
        public string Major { get; set; }
        public Nullable<int> TrainingPlan { get; set; }
        public string Describe { get; set; }
    }
}
