//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt307_InterviewScore
    {
        public int Id { get; set; }
        public string ReportId { get; set; }
        public string InterviewerId { get; set; }
        public string IntervieweeId { get; set; }
        public int ProfessionalSkill { get; set; }
        public string ProfessionalSkillNote { get; set; }
        public int Responsiveness { get; set; }
        public string ResponsivenessNote { get; set; }
        public int Communication { get; set; }
        public string CommunicationNote { get; set; }
        public int ReportQuality { get; set; }
        public string ReportQualityNote { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
