//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt301_CertReqSetting
    {
        public int Id { get; set; }
        public string IdDept { get; set; }
        public string IdJobTitle { get; set; }
        public string IdCourse { get; set; }
        public Nullable<int> NewHeadcount { get; set; }
        public Nullable<int> ActualHeadcount { get; set; }
        public int ReqQuantity { get; set; }
    }
}
