//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt301_Course
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Category { get; set; }
        public string TypeOf { get; set; }
    }
}
