//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt307_Questions
    {
        public int Id { get; set; }
        public string IdJob { get; set; }
        public string DisplayText { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsMultiAns { get; set; }
    }
}
