//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt308_CheckDetail
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int EmpId { get; set; }
        public int HealthRating { get; set; }
        public string Disease1 { get; set; }
        public string Disease2 { get; set; }
        public string Disease3 { get; set; }
    }
}
