//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt309_RecoveryTickets
    {
        public int Id { get; set; }
        public string TicketNo { get; set; }
        public int IssueTransactionId { get; set; }
        public Nullable<int> RestockInTransactionId { get; set; }
        public int NewMaterialId { get; set; }
        public int OldBaseMaterialId { get; set; }
        public Nullable<int> OldRecoveryMaterialId { get; set; }
        public string RecoveryOption { get; set; }
        public double Quantity { get; set; }
        public int SourceStorageId { get; set; }
        public Nullable<int> RestockStorageId { get; set; }
        public string AssignedUserId { get; set; }
        public Nullable<System.DateTime> PlannedDisposeDate { get; set; }
        public Nullable<System.DateTime> ActualDisposeDate { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string ResultNote { get; set; }
        public Nullable<System.DateTime> EvidenceSubmittedDate { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelReason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
