//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt307_JobQuesManage
    {
        public string JobId { get; set; }
        public string IdDept { get; set; }
        public Nullable<int> TestDuration { get; set; }
        public Nullable<int> QuesCount { get; set; }
        public Nullable<int> PassingScore { get; set; }
        public int MultiQues { get; set; }
    }
}
