//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt309_Materials
    {
        public int Id { get; set; }
        public string IdDept { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public string TypeUse { get; set; }
        public string Location { get; set; }
        public int IdUnit { get; set; }
        public double MinQuantity { get; set; }
        public double QuantityInStorage { get; set; }
        public double QuantityInMachine { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string IdManager { get; set; }
        public Nullable<System.DateTime> DelTime { get; set; }
        public string UserDel { get; set; }
        public int Price { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public string DisabledBy { get; set; }
        public Nullable<System.DateTime> DisabledDate { get; set; }
        public string EnabledBy { get; set; }
        public Nullable<System.DateTime> EnabledDate { get; set; }
        public Nullable<int> ReplacementMaterialId { get; set; }
        public Nullable<System.DateTime> ReplacementDate { get; set; }
    }
}
