//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt308_Disease
    {
        public int Id { get; set; }
        public string DisplayNameVN { get; set; }
        public string DisplayNameTW { get; set; }
        public int DiseaseType { get; set; }
    }
}
