//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt302_ReportInfo
    {
        public int Id { get; set; }
        public int IdBase { get; set; }
        public string Content { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
