//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt309_Transactions
    {
        public int Id { get; set; }
        public int StorageId { get; set; }
        public int MaterialId { get; set; }
        public int Quantity { get; set; }
        public string TransactionType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> AftQuantity { get; set; }
        public Nullable<double> TotalQuantity { get; set; }
        public string UserDo { get; set; }
        public string Desc { get; set; }
    }
}
