//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt306_BaseAtts
    {
        public int Id { get; set; }
        public int IdBase { get; set; }
        public int IdAtt { get; set; }
        public string DisplayName { get; set; }
        public bool IsCancel { get; set; }
        public string UsrCancel { get; set; }
        public string Desc { get; set; }
    }
}
