//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt301_Base
    {
        public int Id { get; set; }
        public string IdDept { get; set; }
        public string IdUser { get; set; }
        public string IdJobTitle { get; set; }
        public string IdCourse { get; set; }
        public System.DateTime DateReceipt { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public bool ValidLicense { get; set; }
        public bool BackupLicense { get; set; }
        public bool InvalidLicense { get; set; }
        public string Describe { get; set; }
    }
}
