//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt307_InterviewReport
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Interviewer { get; set; }
        public string Interviewees { get; set; }
        public string Notes { get; set; }
    }
}
