//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt311_InvoiceItem
    {
        public int Id { get; set; }
        public string IdInvoice { get; set; }
        public string LineNumber { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string VATRate { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public string Note { get; set; }
    }
}
