//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt312_ExamMgmt
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int RoundNumber { get; set; }
        public Nullable<System.DateTime> FinishNotifyDate { get; set; }
    }
}
