//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt311_Invoice
    {
        public string TransactionID { get; set; }
        public string SourceType { get; set; }
        public string InvoiceCode { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string BuyerTax { get; set; }
        public string SellerTax { get; set; }
        public Nullable<decimal> TotalBeforeVAT { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> TotalAfterVAT { get; set; }
        public string IdDept { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<int> OdometerReading { get; set; }
        public string FuelFilledBy { get; set; }
        public Nullable<int> AttId { get; set; }
    }
}
