//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt311_VehicleManagement
    {
        public string LicensePlate { get; set; }
        public string ManagerId { get; set; }
        public string IdDept { get; set; }
        public string FuelType { get; set; }
        public string VehicleType { get; set; }
    }
}
