//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt313_FixedAsset
    {
        public int Id { get; set; }
        public string AssetCode { get; set; }
        public string AssetNameTW { get; set; }
        public string AssetNameVN { get; set; }
        public string IdDept { get; set; }
        public string IdManager { get; set; }
        public string AssetCategory { get; set; }
        public string TypeName { get; set; }
        public string Location { get; set; }
        public string BrandSpec { get; set; }
        public string Origin { get; set; }
        public Nullable<System.DateTime> AcquireDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastMonthlyCheckDate { get; set; }
        public Nullable<System.DateTime> LastQuarterlyAuditDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
