//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt310_Area5SResponsible
    {
        public int Id { get; set; }
        public int AreaId { get; set; }
        public string DeptId { get; set; }
        public string EmployeeId { get; set; }
        public string AgentId { get; set; }
        public string BossId { get; set; }
        public string AreaName { get; set; }
        public string AreaCode { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string DeletedBy { get; set; }
    }
}
