//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt313_InspectionBatchAsset
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public int FixedAssetId { get; set; }
        public string Result { get; set; }
        public Nullable<int> AbnormalId { get; set; }
        public string AbnormalNote { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<System.DateTime> CorrectionDueDate { get; set; }
        public string CorrectionStatus { get; set; }
        public string CorrectionNote { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
