//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt310_UpdateLeaveUser
    {
        public int Id { get; set; }
        public string IdUserLeave { get; set; }
        public string DisplayName { get; set; }
        public bool IsProcess { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<int> IdGroupProcess { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
