//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt313_InspectionBatch
    {
        public int Id { get; set; }
        public string BatchName { get; set; }
        public string BatchType { get; set; }
        public string PeriodKey { get; set; }
        public string IdDept { get; set; }
        public string AssignedUserId { get; set; }
        public Nullable<int> SampleRate { get; set; }
        public int TargetQty { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    }
}
