//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt310_UpdateLeaveUser_detail
    {
        public int Id { get; set; }
        public int IdUpdateData { get; set; }
        public int IndexStep { get; set; }
        public int IdGroup { get; set; }
        public string IdUser { get; set; }
        public string DataJson { get; set; }
        public Nullable<System.DateTime> TimeSubmit { get; set; }
        public Nullable<System.DateTime> TimeNotify { get; set; }
        public string Description { get; set; }
    }
}
