//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt403_05_Standard
    {
        public int Id { get; set; }
        public string SN { get; set; }  // 100B-17
        public string DisplayNameTW { get; set; } //塞尺
        public string DisplayNameVN { get; set; } // Bộ căn lá
        public string ManagerId { get; set; }
        public string MaGCN { get; set; } //TSG-0-438208
        public string ĐKĐBĐ { get; set; } //(0.001~0.003) mm(0.001~0.003) mm
        public Nullable<System.DateTime> NextCalibrationDate { get; set; } //2025/07/11
        public string Standardlink { get; set; } // Techmaster
    }
}
