//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt403_05_Standard
    {
        public int Id { get; set; }
        public string SN { get; set; }
        public string DisplayNameTW { get; set; }
        public string DisplayNameVN { get; set; }
        public string ManagerId { get; set; }
        public string MaGCN { get; set; }
        public string ĐKĐBĐ { get; set; }
        public Nullable<System.DateTime> NextCalibrationDate { get; set; }
        public string Standardlink { get; set; }
    }
}
