//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt403_04_HardnessStandardLog
    {
        public int Id { get; set; }
        public System.DateTime TimeCreate { get; set; }
        public string IdDept { get; set; }
        public string MachineName { get; set; }
        public string SampleSN { get; set; }
        public string Method { get; set; }
        public double StandardValue { get; set; }
        public double TestValue { get; set; }
        public double AllowableError { get; set; }
        public string Tester { get; set; }
        public Nullable<System.DateTime> TimeNotify { get; set; }
    }
}
