//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt403_04_HardnessStandardLog
    {
        public int Id { get; set; }
        public string IdDept { get; set; }
        public string MachineName { get; set; }
        public string SampleId { get; set; }
        public string Method { get; set; }
        public double Value1 { get; set; }
        public Nullable<double> Value2 { get; set; }
        public Nullable<double> Value3 { get; set; }
        public Nullable<double> Value4 { get; set; }
        public Nullable<double> Value5 { get; set; }
        public Nullable<System.DateTime> TimeCreate { get; set; }
    }
}
