//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt403_05_StandardAtt
    {
        public int Id { get; set; }
        public int StandardId { get; set; }
        public int AttId { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string UploadUser { get; set; }
        public string ConfirmUser { get; set; }
        public string FinishUser { get; set; }
        public string MaGCN { get; set; }
        public string ĐKĐBĐ { get; set; }
        public Nullable<System.DateTime> NextCalibrationDate { get; set; }
        public string Standardlink { get; set; }
    }
}
