//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt402_KPIWeb
    {
        public int Id { get; set; }
        public string IdUsr { get; set; }
        public string YearMonth { get; set; }
        public string DeptScore { get; set; }
        public string DeptComments { get; set; }
        public string MgrScore { get; set; }
        public string MgrComments { get; set; }
    }
}
