//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDocumentManagementSystemEntities : DbContext
    {
        public DBDocumentManagementSystemEntities()
            : base(SingleConnection.ConString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dm_Function> dm_Function { get; set; }
        public virtual DbSet<dm_FunctionRole> dm_FunctionRole { get; set; }
        public virtual DbSet<dm_GroupUser> dm_GroupUser { get; set; }
        public virtual DbSet<dm_Role> dm_Role { get; set; }
        public virtual DbSet<dm_StepProgress> dm_StepProgress { get; set; }
        public virtual DbSet<dt207_Attachment_BAK> dt207_Attachment_BAK { get; set; }
        public virtual DbSet<dt207_Base_BAK> dt207_Base_BAK { get; set; }
        public virtual DbSet<dt207_NotifyEditDoc> dt207_NotifyEditDoc { get; set; }
        public virtual DbSet<dt207_Security> dt207_Security { get; set; }
        public virtual DbSet<dt207_Security_BAK> dt207_Security_BAK { get; set; }
        public virtual DbSet<dt207_Targets> dt207_Targets { get; set; }
        public virtual DbSet<dt207_Type> dt207_Type { get; set; }
        public virtual DbSet<dt207_TypeHisGetFile> dt207_TypeHisGetFile { get; set; }
        public virtual DbSet<sys_Log> sys_Log { get; set; }
        public virtual DbSet<sys_StaticValue> sys_StaticValue { get; set; }
        public virtual DbSet<dt207_Base> dt207_Base { get; set; }
        public virtual DbSet<dt207_HistoryGetFile> dt207_HistoryGetFile { get; set; }
        public virtual DbSet<dt207_DocProcessing> dt207_DocProcessing { get; set; }
        public virtual DbSet<dt207_DocProcessingInfo> dt207_DocProcessingInfo { get; set; }
        public virtual DbSet<dm_UserRole> dm_UserRole { get; set; }
        public virtual DbSet<dm_Group> dm_Group { get; set; }
        public virtual DbSet<dm_Progress> dm_Progress { get; set; }
        public virtual DbSet<dm_JobTitle> dm_JobTitle { get; set; }
        public virtual DbSet<dt301_CertReqSetting> dt301_CertReqSetting { get; set; }
        public virtual DbSet<dt301_Base> dt301_Base { get; set; }
        public virtual DbSet<sys_NotesMail> sys_NotesMail { get; set; }
        public virtual DbSet<dm_Attachment> dm_Attachment { get; set; }
        public virtual DbSet<dt302_ReportAttach> dt302_ReportAttach { get; set; }
        public virtual DbSet<dt302_Base> dt302_Base { get; set; }
        public virtual DbSet<dt302_ReportInfo> dt302_ReportInfo { get; set; }
        public virtual DbSet<dt202_Type> dt202_Type { get; set; }
        public virtual DbSet<dt202_Attach> dt202_Attach { get; set; }
        public virtual DbSet<dt207_Attachment> dt207_Attachment { get; set; }
        public virtual DbSet<dt202_Base> dt202_Base { get; set; }
        public virtual DbSet<dm_DeptGroups> dm_DeptGroups { get; set; }
        public virtual DbSet<dm_DrivingLic> dm_DrivingLic { get; set; }
        public virtual DbSet<dt201_Role> dt201_Role { get; set; }
        public virtual DbSet<dm_SignUsers> dm_SignUsers { get; set; }
        public virtual DbSet<dt306_BaseAtts> dt306_BaseAtts { get; set; }
        public virtual DbSet<dt306_ProgInfo> dt306_ProgInfo { get; set; }
        public virtual DbSet<dt306_Progress> dt306_Progress { get; set; }
        public virtual DbSet<dm_FixedProgress> dm_FixedProgress { get; set; }
        public virtual DbSet<dt306_SignRole> dt306_SignRole { get; set; }
        public virtual DbSet<dt307_Questions> dt307_Questions { get; set; }
        public virtual DbSet<dt201_UpdateUsrReq> dt201_UpdateUsrReq { get; set; }
        public virtual DbSet<dt402_KPIWeb> dt402_KPIWeb { get; set; }
        public virtual DbSet<dt307_ExamMgmt> dt307_ExamMgmt { get; set; }
        public virtual DbSet<dt307_ExamUser> dt307_ExamUser { get; set; }
        public virtual DbSet<dt307_Answers> dt307_Answers { get; set; }
        public virtual DbSet<dt306_DocType> dt306_DocType { get; set; }
        public virtual DbSet<dt306_FieldType> dt306_FieldType { get; set; }
        public virtual DbSet<dt306_FieldTypeDocType> dt306_FieldTypeDocType { get; set; }
        public virtual DbSet<dt306_Base> dt306_Base { get; set; }
        public virtual DbSet<dt307_JobQuesManage> dt307_JobQuesManage { get; set; }
        public virtual DbSet<dt403_SoftwareManual> dt403_SoftwareManual { get; set; }
        public virtual DbSet<dt201_ProgInfo> dt201_ProgInfo { get; set; }
        public virtual DbSet<dt201_Progress> dt201_Progress { get; set; }
        public virtual DbSet<dt201_Forms> dt201_Forms { get; set; }
        public virtual DbSet<dt204_DocCatorary> dt204_DocCatorary { get; set; }
        public virtual DbSet<dt204_Form> dt204_Form { get; set; }
        public virtual DbSet<dt204_FuncCatorary> dt204_FuncCatorary { get; set; }
        public virtual DbSet<dt204_RelatedDoc> dt204_RelatedDoc { get; set; }
        public virtual DbSet<dt201_Base> dt201_Base { get; set; }
        public virtual DbSet<dt201_RecordCode> dt201_RecordCode { get; set; }
        public virtual DbSet<dt201_ReqUpdateDocs> dt201_ReqUpdateDocs { get; set; }
        public virtual DbSet<dt201_UpdateUsrReq_Detail> dt201_UpdateUsrReq_Detail { get; set; }
        public virtual DbSet<dm_Sign> dm_Sign { get; set; }
        public virtual DbSet<dt204_OldVersion> dt204_OldVersion { get; set; }
        public virtual DbSet<dm_Watermark> dm_Watermark { get; set; }
        public virtual DbSet<dt308_Disease> dt308_Disease { get; set; }
        public virtual DbSet<dt308_CheckDetail> dt308_CheckDetail { get; set; }
        public virtual DbSet<dt308_SpecialUsrCheck> dt308_SpecialUsrCheck { get; set; }
        public virtual DbSet<dt309_MachineMaterials> dt309_MachineMaterials { get; set; }
        public virtual DbSet<dt309_Materials> dt309_Materials { get; set; }
        public virtual DbSet<dt309_Storages> dt309_Storages { get; set; }
        public virtual DbSet<dt309_Units> dt309_Units { get; set; }
        public virtual DbSet<dt309_Prices> dt309_Prices { get; set; }
        public virtual DbSet<dt204_InternalDocMgmt> dt204_InternalDocMgmt { get; set; }
        public virtual DbSet<dt308_CheckSession> dt308_CheckSession { get; set; }
        public virtual DbSet<dt309_InspectionBatchMaterial> dt309_InspectionBatchMaterial { get; set; }
        public virtual DbSet<dt309_Transactions> dt309_Transactions { get; set; }
        public virtual DbSet<dt309_InspectionBatch> dt309_InspectionBatch { get; set; }
        public virtual DbSet<dt301_Course> dt301_Course { get; set; }
        public virtual DbSet<dt403_04_HardnessStandardLog> dt403_04_HardnessStandardLog { get; set; }
        public virtual DbSet<dt403_04_StandardInfo> dt403_04_StandardInfo { get; set; }
        public virtual DbSet<dm_User> dm_User { get; set; }
        public virtual DbSet<dt310_Area5S> dt310_Area5S { get; set; }
        public virtual DbSet<dt310_Role> dt310_Role { get; set; }
        public virtual DbSet<dm_Departments> dm_Departments { get; set; }
        public virtual DbSet<dt310_UnitEHSOrg> dt310_UnitEHSOrg { get; set; }
        public virtual DbSet<dt310_Function> dt310_Function { get; set; }
        public virtual DbSet<dt310_Area5SResponsible> dt310_Area5SResponsible { get; set; }
        public virtual DbSet<dt310_EHSFunction> dt310_EHSFunction { get; set; }
        public virtual DbSet<dt307_InterviewReport> dt307_InterviewReport { get; set; }
        public virtual DbSet<dt307_InterviewScore> dt307_InterviewScore { get; set; }
        public virtual DbSet<dt309_Machines> dt309_Machines { get; set; }
        public virtual DbSet<dt205_Base> dt205_Base { get; set; }
        public virtual DbSet<dt205_Form> dt205_Form { get; set; }
        public virtual DbSet<dt311_VehicleManagement> dt311_VehicleManagement { get; set; }
        public virtual DbSet<dt311_InvoiceItem> dt311_InvoiceItem { get; set; }
        public virtual DbSet<dt311_SellerBuyer> dt311_SellerBuyer { get; set; }
        public virtual DbSet<dt311_Invoice> dt311_Invoice { get; set; }
    }
}
