//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDocumentManagementSystemEntities : DbContext
    {
        public DBDocumentManagementSystemEntities()
            : base("name=DBDocumentManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dm_Departments> dm_Departments { get; set; }
        public virtual DbSet<dm_Function> dm_Function { get; set; }
        public virtual DbSet<dm_FunctionRole> dm_FunctionRole { get; set; }
        public virtual DbSet<dm_GroupUser> dm_GroupUser { get; set; }
        public virtual DbSet<dm_Role> dm_Role { get; set; }
        public virtual DbSet<dm_StepProgress> dm_StepProgress { get; set; }
        public virtual DbSet<dt207_Attachment> dt207_Attachment { get; set; }
        public virtual DbSet<dt207_Attachment_BAK> dt207_Attachment_BAK { get; set; }
        public virtual DbSet<dt207_Base_BAK> dt207_Base_BAK { get; set; }
        public virtual DbSet<dt207_NotifyEditDoc> dt207_NotifyEditDoc { get; set; }
        public virtual DbSet<dt207_Security> dt207_Security { get; set; }
        public virtual DbSet<dt207_Security_BAK> dt207_Security_BAK { get; set; }
        public virtual DbSet<dt207_Targets> dt207_Targets { get; set; }
        public virtual DbSet<dt207_Type> dt207_Type { get; set; }
        public virtual DbSet<dt207_TypeHisGetFile> dt207_TypeHisGetFile { get; set; }
        public virtual DbSet<sys_Log> sys_Log { get; set; }
        public virtual DbSet<sys_StaticValue> sys_StaticValue { get; set; }
        public virtual DbSet<dt207_Base> dt207_Base { get; set; }
        public virtual DbSet<dt207_HistoryGetFile> dt207_HistoryGetFile { get; set; }
        public virtual DbSet<dt207_DocProcessing> dt207_DocProcessing { get; set; }
        public virtual DbSet<dt207_DocProcessingInfo> dt207_DocProcessingInfo { get; set; }
        public virtual DbSet<dm_UserRole> dm_UserRole { get; set; }
        public virtual DbSet<dm_User> dm_User { get; set; }
        public virtual DbSet<dm_Group> dm_Group { get; set; }
        public virtual DbSet<dm_Progress> dm_Progress { get; set; }
        public virtual DbSet<dm_JobTitle> dm_JobTitle { get; set; }
        public virtual DbSet<dt301_Course> dt301_Course { get; set; }
    }
}
