//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_NotesMail
    {
        public int Id { get; set; }
        public string Thread { get; set; }
        public string Subjects { get; set; }
        public string Content { get; set; }
        public string ToUsers { get; set; }
        public string CCUsers { get; set; }
        public string Attachments { get; set; }
        public Nullable<System.DateTime> TimeNotify { get; set; }
    }
}
