//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw310_EquipmentInfo
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string DisplayNameVN { get; set; }
        public string DisplayNameTW { get; set; }
        public string DeptId { get; set; }
        public string DeptNameTW { get; set; }
        public string DeptNameVN { get; set; }
        public string ManagerId { get; set; }
        public string ManagerNameTW { get; set; }
        public string ManagerNameVN { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
