//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeSystem
{
    public class dt207_Attachment_BAK
    {
        public int Id { get; set; }
        public string IdKnowledgeBase { get; set; }
        public string EncryptionName { get; set; }
        public string FileName { get; set; }
    }
}