//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEF
{
    public class dm_Departments
    {
        public string Id { get; set; }
        public int IdChild { get; set; }
        public int IdParent { get; set; }
        public string DisplayName { get; set; }
    }
}