//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataEF
{
    public class dt207_NotifyEditDoc
    {
        public int Id { get; set; }
        public DateTime TimeNotify { get; set; }
        public int IdDocProcess { get; set; }
        public string IdUserNotify { get; set; }
        public bool IsRead { get; set; }
        public DateTime? TimeNotifyNotes { get; set; }
    }
}