//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataEF
{
    public class dt207_Base_BAK
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> IdTypes { get; set; }
        public string Keyword { get; set; }
        public string UserUpload { get; set; }
        public string UserProcess { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}