//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataEF
{
    public class dt207_DocProgressInfo
    {
        public int Id { get; set; }
        public int IdDocProgress { get; set; }
        public DateTime TimeStep { get; set; }
        public int IndexStep { get; set; }
        public string IdUserProcess { get; set; }
        public string Descriptions { get; set; }
        public DateTime? TimeNotifyNotes { get; set; }
    }
}