//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataEF
{
    public class Function
    {
        public int Id { get; set; }
        public Nullable<int> IdParent { get; set; }
        public string DisplayName { get; set; }
        public string ControlName { get; set; }
        public Nullable<int> Prioritize { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Images { get; set; }
        public bool SetPermission { get; set; }

        public SvgImage ImageLive
        {
            get
            {
                return string.IsNullOrEmpty(Images) ?
                    SvgImage.FromFile($@"Images\none.svg") :
                    SvgImage.FromFile($@"Images\{Images}");
            }
            set { }
        }
    }
}