//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataEF
{
    public class FunctionRole
    {
        public int Id { get; set; }
        public Nullable<int> IdFunction { get; set; }
        public Nullable<int> IdRole { get; set; }
    }
}