//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataEF
{
    public partial class Group
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Describe { get; set; }
        public Nullable<int> Prioritize { get; set; }
    }

    public class GroupProgress : Group
    {
        public int IndexStep { get; set; }
    }
}