//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataEF
{
    public class User
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> IdRole { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string IdDepartment { get; set; }
        public string SecondaryPassword { get; set; }
    }
}