//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDocumentManagementSystemEntities : DbContext
    {
        public DBDocumentManagementSystemEntities()
            : base("name=DBDocumentManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dm_Departments> dm_Departments { get; set; }
        public virtual DbSet<dm_Progress> dm_Progress { get; set; }
        public virtual DbSet<dm_StepProgress> dm_StepProgress { get; set; }
        public virtual DbSet<FunctionRole> FunctionRoles { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<KnowledgeTypeHisGetFile> KnowledgeTypeHisGetFiles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<tbl207_NotifyEditDoc> tbl207_NotifyEditDoc { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<dt207_DocProgress> dt207_DocProgress { get; set; }
        public virtual DbSet<dt207_Base> dt207_Base { get; set; }
        public virtual DbSet<dt207_DocProgressInfo> dt207_DocProgressInfo { get; set; }
        public virtual DbSet<dt207_Attachment> dt207_Attachment { get; set; }
        public virtual DbSet<dt207_HistoryGetFile> dt207_HistoryGetFile { get; set; }
        public virtual DbSet<dt207_Security> dt207_Security { get; set; }
        public virtual DbSet<dt207_Type> dt207_Type { get; set; }
    }
}
